name: Build
on:
  # Trigger the workflow on any pull request
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./orx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: ./orx

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Checkout OPENRNDR repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: openrndr/openrndr
          path: ./openrndr
          ref: master

      - name: Test glxinfo
        run: |
          sudo apt-get install -y mesa-utils xvfb
          xvfb-run glxinfo

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build OPENRNDR
        working-directory: ./openrndr
        run: ./gradlew publishToMavenLocal -Prelease.version=0.5.1-SNAPSHOT

      - name: Build ORX
        run: ./gradlew build

      - name: Collect screenshots without errors
        run: xvfb-run ./gradlew collectScreenshots